module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'Users',
      [{
        first_name: 'Crichton',
        last_name: 'Porcher',
        email: 'cporcher0@amazon.de',
        password: 'OobcmFWoLvF',
        role_id: 6,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Thane',
        last_name: "O'Howbane",
        email: 'tohowbane1@w3.org',
        password: 'FMyNQ0leh',
        role_id: 6,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Wandis',
        last_name: 'Itzhak',
        email: 'witzhak2@goo.gl',
        password: 'ZLlAN0xs',
        role_id: 2,
        department_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Martainn',
        last_name: 'Jarrell',
        email: 'mjarrell3@rakuten.co.jp',
        password: 'IkXcgrE',
        role_id: 7,
        department_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Luise',
        last_name: 'Gomery',
        email: 'lgomery4@nymag.com',
        password: 'VOtW5vI',
        role_id: 7,
        department_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Lindie',
        last_name: 'Artois',
        email: 'lartois5@army.mil',
        password: 'OHXWBd2',
        role_id: 9,
        department_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Bella',
        last_name: 'Haddinton',
        email: 'bhaddinton6@latimes.com',
        password: 'bEQCfEtG0F',
        role_id: 4,
        department_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Edd',
        last_name: 'Gamlin',
        email: 'egamlin7@fema.gov',
        password: 'gWO98qTQbD',
        role_id: 4,
        department_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Tito',
        last_name: 'Orthmann',
        email: 'torthmann8@hugedomains.com',
        password: 's2FvdPcDhjHx',
        role_id: 8,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Bettye',
        last_name: 'Mottershead',
        email: 'bmottershead9@nps.gov',
        password: 'hBSSS8RRI6s',
        role_id: 4,
        department_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Rey',
        last_name: 'Chritchley',
        email: 'rchritchleya@economist.com',
        password: 'r9Rw65pFRxGs',
        role_id: 7,
        department_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Gary',
        last_name: 'Pembry',
        email: 'gpembryb@instagram.com',
        password: 'qZ5uLuqGjts',
        role_id: 4,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Giselbert',
        last_name: 'Luckings',
        email: 'gluckingsc@parallels.com',
        password: 'inP9154',
        role_id: 3,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Aggie',
        last_name: 'Braysher',
        email: 'abraysherd@yolasite.com',
        password: 'xdCbu6Kb6cVN',
        role_id: 5,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Rea',
        last_name: 'Hablet',
        email: 'rhablete@google.com.au',
        password: 'YoFoJA3nm86',
        role_id: 10,
        department_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Cicily',
        last_name: 'Flade',
        email: 'cfladef@java.com',
        password: '5DmS8l',
        role_id: 8,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Sherrie',
        last_name: 'Jeppe',
        email: 'sjeppeg@mapquest.com',
        password: '96BK5cvUSM',
        role_id: 8,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Sherwin',
        last_name: 'Semmens',
        email: 'ssemmensh@privacy.gov.au',
        password: 'lEximOiBToG',
        role_id: 3,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Bebe',
        last_name: 'Adamek',
        email: 'badameki@deliciousdays.com',
        password: 'QF9vYipC7F9I',
        role_id: 9,
        department_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Kennie',
        last_name: 'Horsey',
        email: 'khorseyj@go.com',
        password: '8ZwALRaVT',
        role_id: 10,
        department_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Demetris',
        last_name: 'Evanson',
        email: 'devansonk@mtv.com',
        password: 'fJ9J7AXK',
        role_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Betteanne',
        last_name: 'Blaisdale',
        email: 'bblaisdalel@xinhuanet.com',
        password: 'hDkhVVwQTuO',
        role_id: 3,
        department_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Tobe',
        last_name: 'Maun',
        email: 'tmaunm@epa.gov',
        password: 'Qt9GY9',
        role_id: 3,
        department_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Sansone',
        last_name: 'Kochel',
        email: 'skocheln@tinyurl.com',
        password: 'j72jDr4ScS',
        role_id: 6,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Maddy',
        last_name: 'Jojic',
        email: 'mjojico@go.com',
        password: '9oMEwrEMBOv',
        role_id: 9,
        department_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Agnese',
        last_name: 'Lindup',
        email: 'alindupp@miibeian.gov.cn',
        password: 'Liert9h',
        role_id: 3,
        department_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Cy',
        last_name: 'Vidler',
        email: 'cvidlerq@purevolume.com',
        password: 'lEadEU8',
        role_id: 6,
        department_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Blair',
        last_name: 'Heggison',
        email: 'bheggisonr@phpbb.com',
        password: 'ZODLzG6MsR',
        role_id: 7,
        department_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Herrick',
        last_name: 'Marc',
        email: 'hmarcs@csmonitor.com',
        password: 'rrzEDp3',
        role_id: 3,
        department_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Noll',
        last_name: 'Stott',
        email: 'nstottt@bbb.org',
        password: 'cqA3BgS7FV',
        role_id: 6,
        department_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, {
        first_name: 'Noah',
        last_name: 'Resdale',
        email: 'nresdales@eventbrite.com',
        password: '1UZisEwE8Ri',
        role_id: 3,
        department_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        first_name: 'Izzy',
        last_name: 'Fincke',
        email: 'hmarcs@csmonitor.com',
        password: 'rrzEDp3',
        role_id: 3,
        department_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }],
      {},
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
